acc_cluster:
  - Name: head
  - DMA:
    - Name: head_dma
      MaxReqSize: 64
      BufferSize: 128
      PIOMaster: LocalBus
      Type: NonCoherent
  - DMA:
    - Name: head_stream_dma0
      PIOMaster: LocalBus
      StreamSize: 8
      BufferSize: 64
      Type: Stream
  - Accelerator:
    - Name: head_Top
      IrPath: benchmarks/mobilenetv2/hw/ir/head/top.ll
      ConfigPath: benchmarks/mobilenetv2/hw/configs/head/top.ini
      PIOSize: 65
      PIOMaster: LocalBus
      # Local to PIO
      LocalSlaves: LocalBus
      Debug: False
  - Accelerator:
    - Name: head_NormalConv
      IrPath: benchmarks/mobilenetv2/hw/ir/head/NormalConv.ll
      ConfigPath: benchmarks/mobilenetv2/hw/configs/head/NormalConv.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
      StreamOut: head_stream_dma0
    - Var:
      - Name: head_NormalConvWindow
        Type: SPM
        Size: 27
        Ports: 27
    - Var:
      - Name: head_NormalConvWeights
        Type: SPM
        Size: 864
        Ports: 27
    - Var:
      - Name: head_NormalConvBias
        Type: SPM
        Size: 32
        Ports: 1
    - Var:
      - Name: head_NormalConvIMultBias
        Type: SPM
        Size: 32
        Ports: 1
    - Var:
      - Name: head_NormalConvNShiftBias
        Type: SPM
        Size: 32
        Ports: 1
    - Var:
      - Name: head_NormalConvIMultOut
        Type: SPM
        Size: 32
        Ports: 1
    - Var:
      - Name: head_NormalConvNShiftOut
        Type: SPM
        Size: 32
        Ports: 1
    - Var:
      - Name: head_NormalConvWeightZP
        Type: SPM
        Size: 32
        Ports: 1
    - Var:
      - Name: head_NormalConvQBuffer
        Type: SPM
        Size: 576
        Ports: 2
    - Var:
      - Name: head_NormalConvOut
        Type: Stream
        StreamSize: 8
        BufferSize: 64
        InCon: head_NormalConv
        OutCon: head_DWConv
  - Accelerator:
    - Name: head_DWConv
      IrPath: benchmarks/mobilenetv2/hw/ir/head/DWConv.ll
      ConfigPath: benchmarks/mobilenetv2/hw/configs/head/DWConv.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: head_DWConvWindow
        Type: SPM
        Size: 288
        Ports: 9
    - Var:
      - Name: head_DWConvWeights
        Type: SPM
        Size: 320
        Ports: 9
    - Var:
      - Name: head_DWConvBias
        Type: SPM
        Size: 32
        Ports: 1
    - Var:
      - Name: head_DWConvIMultBias
        Type: SPM
        Size: 32
        Ports: 1
    - Var:
      - Name: head_DWConvNShiftBias
        Type: SPM
        Size: 32
        Ports: 1
    - Var:
      - Name: head_DWConvIMultOut
        Type: SPM
        Size: 32
        Ports: 1
    - Var:
      - Name: head_DWConvNShiftOut
        Type: SPM
        Size: 32
        Ports: 1
    - Var:
      - Name: head_DWConvWeightZP
        Type: SPM
        Size: 32
        Ports: 1
    - Var:
      - Name: head_DWConvQBuffer
        Type: SPM
        Size: 3072
        Ports: 2
    - Var:
      - Name: head_DWConvOutBuffer
        Type: SPM
        Size: 32
        Ports: 1
    - Var:
      - Name: head_DWConvOut
        Type: Stream
        StreamSize: 8
        BufferSize: 64
        InCon: head_DWConv
        OutCon: head_PWConv
  - Accelerator:
    - Name: head_PWConv
      IrPath: benchmarks/mobilenetv2/hw/ir/head/PWConv.ll
      ConfigPath: benchmarks/mobilenetv2/hw/configs/head/PWConv.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
      StreamIn: head_stream_dma0
    - Var:
      - Name: head_PWConvLocalFeats
        Type: SPM
        Size: 32
        Ports: 24
    - Var:
      - Name: head_PWConvWeights
        Type: SPM
        Size: 512
        Ports: 24
    - Var:
      - Name: head_PWConvBias
        Type: SPM
        Size: 16
        Ports: 1
    - Var:
      - Name: head_PWConvIMultBias
        Type: SPM
        Size: 16
        Ports: 1
    - Var:
      - Name: head_PWConvNShiftBias
        Type: SPM
        Size: 16
        Ports: 1
    - Var:
      - Name: head_PWConvIMultOut
        Type: SPM
        Size: 16
        Ports: 1
    - Var:
      - Name: head_PWConvNShiftOut
        Type: SPM
        Size: 16
        Ports: 1
    - Var:
      - Name: head_PWConvWeightZP
        Type: SPM
        Size: 16
        Ports: 1