acc_cluster:
 - SysPath: "configs/sys_configs/head.yml"
 - HWPath: "configs/hw_configs/head.yml"
---
acc_cluster:
 - SysPath: "configs/sys_configs/body.yml"
 - HWPath: "configs/hw_configs/body.yml"
---
acc_cluster:
 - SysPath: "configs/sys_configs/tail.yml"
 - HWPath: "configs/hw_configs/tail.yml"
---
acc_cluster:
 - SysPath: "configs/sys_configs/classifier.yml"
 - HWPath: "configs/hw_configs/classifier.yml"